### ISSUE TITLE
balance starts in back-to-back pairings

### ISSUE THREAD

**Issue by martindemello** [cocoscrabble/googlesheets-tournament-script#7]
One player (Winter) complained that he had back-to-back pairings against the same opponent (Jason Keller) and was assigned to go twice both games. I know we've tweaked the balancing of the firsts and seconds and am not sure if it's correct or possible to have the script take into account who went first in prior matchups against the same opponent. I have not reviewed the firsts/seconds to see whether Keller simply had fewer firsts than Winter when the second matchup occurred, but I understand Winter's comment that it's disheartening to play the same person twice and go second both times.

**Comment by martindemello** [comment]
this is probably not feasible; e.g. if player1 has 3 starts and player2 has 5 starts, then if they play each other twice running player1 will start both times. anything else would disrupt the global start balancing.

**Comment by kempii8** [comment]
I agree with your comment above where there is an unequal number of starts. If they have equal starts, then the script will prioritize giving the start to the player who last went second, correct?

**Comment by martindemello** [comment]
yes, that should work as soon as I upload the new version of the script!

**Comment by martindemello** [comment]
test notifications

**Comment by kempii8** [comment]
Received
